# Generated by Django 5.2.11 on 2026-02-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('hero_overlay_title', models.CharField(default='"אם היית פרח"', max_length=200)),
                ('hero_overlay_text', models.TextField(default='סדנה נשית חוויתית ומקצועית ומותאמת לעולם הארגוני')),
                ('hero_overlay_image', models.ImageField(blank=True, help_text='Flower image', null=True, upload_to='hero/')),
                ('hero_subtitle', models.CharField(default='הסדנה מיועדת לנשים בגיל 40+', max_length=300)),
                ('hero_cta_text', models.CharField(default='לתיאום סדנאות', max_length=100)),
                ('hero_cta_link', models.URLField(blank=True, default='#contact')),
            ],
            options={
                'verbose_name': 'דף בית',
                'verbose_name_plural': 'דף בית',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('logo_text', models.ImageField(blank=True, help_text='Logo text image (תבונת המעבר)', null=True, upload_to='site/')),
                ('header_tagline', models.CharField(default='מרחב לנשים באמצע החיים', max_length=300)),
            ],
            options={
                'verbose_name': 'הגדרות אתר',
                'verbose_name_plural': 'הגדרות אתר',
            },
        ),
    ]
