# Generated by Django 5.0 on 2026-03-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='facilitators_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/facilitators/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section2_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/section2/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section3_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/section3/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section3_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/section3/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section3_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/section3/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section3_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/section3/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section4_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/section4/'),
        ),
    ]
