# Generated by Django 5.0 on 2026-03-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0002_homepage_image_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='משפט')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='סדר')),
            ],
            options={
                'verbose_name': 'ציטוט (סקשן 6)',
                'verbose_name_plural': 'ציטוטים (סקשן 6)',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
