# Generated by Django 5.0 on 2026-03-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0006_remove_year_from_hero_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section7Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='סדר (1–6)')),
                ('text', models.TextField(blank=True, help_text='אם ריק – יוצג הטקסט הקבוע של אותו מקום (ברירת מחדל).', verbose_name='טקסט')),
            ],
            options={
                'verbose_name': 'משתתפת משתפת (סקשן 7)',
                'verbose_name_plural': 'משתתפות משתפות (סקשן 7)',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'תמונות דף הבית', 'verbose_name_plural': 'תמונות דף הבית'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='facilitators_image',
            field=models.ImageField(blank=True, help_text='מומלץ: 400×400 פיקסלים (יוצג כעיגול 358×358).', null=True, upload_to='homepage/facilitators/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='מומלץ: 1920×1080 פיקסלים (באנר רוחב מלא, גובה 660px באתר).', null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_overlay_image',
            field=models.ImageField(blank=True, help_text='תמונת פרח. מומלץ: 80×80 עד 160×160 פיקסלים.', null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_overlay_text',
            field=models.TextField(default='סדנה נשית\nחוויתית ומקצועית לגיל 40 +\nמותאמת לעולם הארגוני'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section2_image',
            field=models.ImageField(blank=True, help_text='מומלץ: כ־800×1000 פיקסלים (חצי רוחב המסך, גובה חופשי).', null=True, upload_to='homepage/section2/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section3_image_1',
            field=models.ImageField(blank=True, help_text='מומלץ: 250×250 פיקסלים (יוצג כעיגול 214×214).', null=True, upload_to='homepage/section3/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section3_image_2',
            field=models.ImageField(blank=True, help_text='מומלץ: 250×250 פיקסלים (יוצג כעיגול 214×214).', null=True, upload_to='homepage/section3/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section3_image_3',
            field=models.ImageField(blank=True, help_text='מומלץ: 250×250 פיקסלים (יוצג כעיגול 214×214).', null=True, upload_to='homepage/section3/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section3_image_4',
            field=models.ImageField(blank=True, help_text='מומלץ: 250×250 פיקסלים (יוצג כעיגול 214×214).', null=True, upload_to='homepage/section3/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='section4_image',
            field=models.ImageField(blank=True, help_text='מומלץ: 720×500 פיקסלים (חצי רוחב, גובה 500px באתר).', null=True, upload_to='homepage/section4/'),
        ),
    ]
